# The URL the site will be built for
base_url = "https://maddyinadream.vercel.app"
theme = "zap"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
inline_icons = true
icons = ["home", "chat", "search", "light", "asleep", "rss"]
keywords = "blog, personal, writing"

menu_links = [
  { url = "$BASE_URL/", name = "Home", icon = "home.svg" },
  { url = "$BASE_URL/posts/", name = "Posts", icon = "chat.svg" },
]
